### ISSUE TITLE
Doesn't ignore comments

### ISSUE THREAD

**Issue by rgrinberg** [rdolgushin/gitignore.vim#2]
For example, the following .gitignore file will fail to read:

https://github.com/ocaml/ocaml//blob/bee55c46e931fb987f9ecae60c891939e8208506/.gitignore

**Comment by rdolgushin** [comment]
Which version of Vim you are using?
I can't to reproduce such bug with 7.4.712 at least.

**Comment by rgrinberg** [comment]
I'm using neovim-head.

**Comment by rdolgushin** [comment]
Hmm... Any suggestions?

**Comment by rgrinberg** [comment]
Strangely enough, I can no longer reproduce this. If I'll see the error again I'll reopen.
